### PR TITLE
downgrade androidx core to 1.7.0

### PR DESCRIPTION
**Pull request by alexander-kulikovskii**
Downgrade androix core to pass metalava checks for current kotlin version (`1.5.31`).
With current core version (`1.8.0`) we not compatible with current Kotlin version, because it's required 1.6.+.

## Pull request checklist:
 - [ ] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
    
 - [ ] Write tests for all new functionality. If tests were not written, please explain why.
 - [ ] Optimize code for java consumption (`@JvmOverloads`, `@file:JvmName`, etc).
 - [ ] Add example if relevant.
 - [ ] Document any changes to public APIs.
 - [ ] Run `make update-api` to update generated api files, if there's public API changes, otherwise the `verify-api-*` CI steps might fail.
 - [x] Update [CHANGELOG.md](../CHANGELOG.md) or use the label 'skip changelog', otherwise `check changelog` CI step will fail.
 - [ ] If this PR is a `v10.[version]` release branch fix / enhancement, merge it to `main` firstly and then port to `v10.[version]` release branch.

Fixes: < Link to related issues that will be fixed by this pull request, if they exist >

PRs must be submitted under the terms of our Contributor License Agreement [CLA](https://github.com/mapbox/mapbox-maps-android/blob/main/CONTRIBUTING.md#contributor-license-agreement).

### CODE REVIEW

**Comment by yunikkk** [comment]
@alexander-kulikovskii is there any description on why metalava fails with newer kotlin libs? Is it kotlin version? Would be nice to add a comment it seems

**Comment by pengdev** [comment]
@alexander-kulikovskii please also run make update-api to update the metalava and api files.

**Comment by alexander-kulikovskii** [comment]
> @alexander-kulikovskii please also run make update-api to update the metalava and api files.

done

**Comment by alexander-kulikovskii** [comment]
> @alexander-kulikovskii is there any description on why metalava fails with newer kotlin libs? Is it kotlin version? Would be nice to add a comment it seems

done

**Review by pengdev — APPROVED** [review]

**Review by yunikkk — APPROVED** [review]

**Review by ank27 — APPROVED** [review]

**Review by Chaoba — APPROVED** [review]

**Pull request merged**
