### PR TITLE
Add showLogo and showAttributes config for snapshotter

### PR DESCRIPTION
**Pull request by Chaoba**
PRs must be submitted under the terms of our Contributor License Agreement [CLA](https://github.com/mapbox/mapbox-maps-android/blob/main/CONTRIBUTING.md#contributor-license-agreement).
Fixes: < Link to related issues that will be fixed by this pull request, if they exist >

## Pull request checklist:
 - [x] Briefly describe the changes in this PR.
 - [x] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality. If tests were not written, please explain why.
 - [ ] Add example if relevant.
 - [ ] Document any changes to public APIs.
 - [x] Apply changelog label ('breaking change', 'bug :beetle:', 'build', 'docs', 'feature :green_apple:', 'performance :zap:', 'testing :100:') or use the label 'skip changelog'
 - [x] Add an entry inside this element for inclusion in the `mapbox-maps-android` changelog: `<changelog>Add showLogo and showAttributes config for snapshotter. User can then hide logo and attributions in a snapshotter</changelog>`.

### Summary of changes
Created a new data class `SnapshotOptions` which wrap `MapSnapshotOptions` and `showLogo`/`showAttribution`. 
`Snapshotter` now take a `SnapshotOptions` as construct param.
image
image
image

### CODE REVIEW

**Review by kiryldz — COMMENTED** [review]
@Chaoba 
1. can we have a unit test verifying that when we set new flags to false - we do not call `drawAttribution` and `drawLogo`?
2. why is it a breaking change? having default values should not make it a breaking change I assume

**Comment by kiryldz** [comment]
> @Chaoba
> 
> 1. can we have a unit test verifying that when we set new flags to false - we do not call `drawAttribution` and `drawLogo`?
> 2. why is it a breaking change? having default values should not make it a breaking change I assume

I see now that it's a breaking change because of metrics CI bot. Is there perhaps a way to not make it a breaking change somehow? Although I'm fine if it is

**Comment by Chaoba** [comment]
> > @Chaoba
> > 
> > 1. can we have a unit test verifying that when we set new flags to false - we do not call `drawAttribution` and `drawLogo`?
> > 2. why is it a breaking change? having default values should not make it a breaking change I assume
> 
> I see now that it's a breaking change because of metrics CI bot. Is there perhaps a way to not make it a breaking change somehow? Although I'm fine if it is

Another solution is to let the SnapshottOptions only contain `drawAttribution` and `drawLogo` and have a default value as the last param of constructor method of `Snapshotter`. @tobrun What do you think?

**Comment by Chaoba** [comment]
> @Chaoba
> 
> 1. can we have a unit test verifying that when we set new flags to false - we do not call `drawAttribution` and `drawLogo`?
> 2. why is it a breaking change? having default values should not make it a breaking change I assume

It's very different to test the snapshotter callback. Guess we can add an instrumentation test when we have a pixel compare test.

**Comment by tobrun** [comment]
> Another solution is to let the SnapshottOptions only contain drawAttribution and drawLogo and have a default value as the last param of constructor method of Snapshotter. @tobrun What do you think?

Maybe that is better.. and have the default values being set to true

**Review by kiryldz — APPROVED** [review]
LGTM (the only concern left is not having a test for that but if I got correctly only pixel-match tests could help us here)

**Pull request merged**
