### PR TITLE
[gestures] Introduce platform-driven drag API to move a map

### PR DESCRIPTION
**Pull request by kiryldz**
PRs must be submitted under the terms of our Contributor License Agreement [CLA](https://github.com/mapbox/mapbox-maps-android/blob/main/CONTRIBUTING.md#contributor-license-agreement).
Fixes: < Link to related issues that will be fixed by this pull request, if they exist >

## Pull request checklist:
 - [x] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [x] Write tests for all new functionality. If tests were not written, please explain why.
 - [ ] Add example if relevant.
 - [ ] Document any changes to public APIs.
 - [x] Apply changelog label ('breaking change', 'bug :beetle:', 'build', 'docs', 'feature :green_apple:', 'performance :zap:', 'testing :100:') or use the label 'skip changelog'
 - [x] Add an entry inside this element for inclusion in the `mapbox-maps-android` changelog: `<changelog>[gestures] Introduce platform-driven drag API to move a map</changelog>`.

### Summary of changes

All gestures related to moving a map following if necessary with fling animation afterwards are now considered to use __drag API__. This API is designed to work both with or without 3D Terrain and should use following functions:
 - `dragStart` - must be called before map starts dragging
 - `getDragCameraOptions` - used to calculate correctly elevated `CameraOptions` that is used as target point for `easeTo` animation
 - `dragEnd` - must be called when dragging a map has finished.

Dragging means operating with `center` animator only as part of `CameraOptions`.

### CODE REVIEW

**Comment by pengdev** [comment]
@kiryldz could you attach a gif or video of the visual changes?

**Comment by kiryldz** [comment]
> @kiryldz could you attach a gif or video of the visual changes?

There are no visual changes, we just do dragging using platform animation now.

**Review by pengdev — APPROVED** [review]
LGTM

**Review by tobrun — APPROVED** [review]
:shipit:

**Pull request merged**
