### PR TITLE
[docs] update api reference for v10.0.0-beta.13

### PR DESCRIPTION
**Pull request by tobrun**
Update API reference documentation for v10.0.0-beta.13:
 - https://github.com/mapbox/mapbox-maps-android/releases/tag/android-v10.0.0-beta.13

### CODE REVIEW

**Comment by pengdev** [comment]
> No configuration was found in your project.

Is this expected?

**Comment by tobrun** [comment]
Yes, the publisher production branch doesn't have circle.yml file

**Review by pengdev — APPROVED** [review]

**Review by danswick — APPROVED** [review]
Looks good! Thanks, @tobrun. 

Just a side-note: I noticed that the dokka doc are about an order of magnitude larger in size than the javadoc ones. I looked through the files and didn't notice anything that looks unusual, but just wanted to note in case it's unexpected to you.

**Comment by tobrun** [comment]
> Just a side-note: I noticed that the dokka doc are about an order of magnitude larger in size than the javadoc ones. I looked through the files and didn't notice anything that looks unusual, but just wanted to note in case it's unexpected to you.

It's a complete new system so I'm not surprised.

**Pull request merged**
