### PR TITLE
WaitForIdle before perform flaky instrumentation test

### PR DESCRIPTION
**Pull request by axti**
PRs must be submitted under the terms of our Contributor License Agreement [CLA](https://github.com/mapbox/mapbox-maps-android/blob/main/CONTRIBUTING.md#contributor-license-agreement).
Fixes: < Link to related issues that will be fixed by this pull request, if they exist >

## Pull request checklist:
 - [x] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality. If tests were not written, please explain why.
 - [ ] Optimize code for java consumption (`@JvmOverloads`, `@file:JvmName`, etc).
 - [ ] Add example if relevant.
 - [ ] Document any changes to public APIs.
 - [x] Apply changelog label ('breaking change', 'bug :beetle:', 'build', 'docs', 'feature :green_apple:', 'performance :zap:', 'testing :100:') or use the label 'skip changelog'
 - [ ] Add an entry inside this element for inclusion in the `mapbox-maps-android` changelog: `<changelog></changelog>`.

### Summary of changes
Added waitForIdle in flaky instrumentation test before performing rotations.
With measures on emulator this command added around 800ms before changing rotation, so luckily it should solve the problem with full initialisation of views.

### CODE REVIEW

**Comment by kiryldz** [comment]
@axti I'm a bit confused, PR states that wait for idle was added while looking at the files I see that all waiting for idle events where actually removed between `device.setOrientationNatural()` and other calls.

Did we even see those tests being flaky at all? I can't recall such errors on the CI recently

**Comment by axti** [comment]
> @axti I'm a bit confused, PR states that wait for idle was added while looking at the files I see that all waiting for idle events where actually removed between `device.setOrientationNatural()` and other calls.
> 
> Did we even see those tests being flaky at all? I can't recall such errors on the CI recently

We add one `device.waitForIdle()` before test start rotating action and delete redundant calls between since inside every calls for rotation it is contains waitForIdle after actual rotation.

**Review by kiryldz — APPROVED** [review]
@axti thanks for clarification, LGTM

**Review by ank27 — APPROVED** [review]

**Comment by ank27** [comment]
just fyi : you don't need to check changelog item. when you have `skip_changelog` label

LGTM

**Pull request merged**
