### PR TITLE
Fix permissions for e2e scripts

### PR DESCRIPTION
**Pull request by kiryldz**
### Summary of changes
E2E was not triggered neither for PR (but due to a check e2e was always green) nor for merge to `main` (in that case it was failing).
Granted `u+x` permissions for the scripts to allow actually executing and also fixed arguments so it does actually work now.

## Pull request checklist:
 - [x] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
    
 - [ ] Write tests for all new functionality. If tests were not written, please explain why.
 - [ ] Optimize code for java consumption (`@JvmOverloads`, `@file:JvmName`, etc).
 - [ ] Add example if relevant.
 - [ ] Document any changes to public APIs.
 - [ ] Run `make update-api` to update generated api files, if there's public API changes, otherwise the `verify-api-*` CI steps might fail.
 - [ ] Update [CHANGELOG.md](../CHANGELOG.md) or use the label 'skip changelog', otherwise `check changelog` CI step will fail.
 - [x] If this PR is a `v10.[version]` release branch fix / enhancement, merge it to `main` firstly and then port to `v10.[version]` release branch.

Fixes: < Link to related issues that will be fixed by this pull request, if they exist >

PRs must be submitted under the terms of our Contributor License Agreement [CLA](https://github.com/mapbox/mapbox-maps-android/blob/main/CONTRIBUTING.md#contributor-license-agreement).

### CODE REVIEW

**Review by yunikkk — APPROVED** [review]

**Comment by yunikkk** [comment]
How have you noticed the error?

**Review by alexander-kulikovskii — APPROVED** [review]

**Review by ank27 — APPROVED** [review]

**Comment by pengdev** [comment]
Or we can add `python3` at the beginning when executing these scripts, but I guess it's also fine to add the permission here.

**Review by pengdev — APPROVED** [review]

**Comment by kiryldz** [comment]
> Or we can add `python3` at the beginning when executing these scripts, but I guess it's also fine to add the permission here.

We still need to execute `ci-e2e-job-trigger-checker.sh`, so changing permissions is better.

**Comment by kiryldz** [comment]
> How have you noticed the error?

I have a 💎 👁️

**Pull request merged**
