### PR TITLE
[port] bump gl native 10.8.0

### PR DESCRIPTION
**Pull request by alexander-kulikovskii**
This PR ports https://github.com/mapbox/mapbox-maps-android/pull/1650 to v10.8 release branch.

Also leave date empty and revert back readme files. All changes should be done with new release-train

## Pull request checklist:
 - [ ] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
    
 - [ ] Write tests for all new functionality. If tests were not written, please explain why.
 - [ ] Optimize code for java consumption (`@JvmOverloads`, `@file:JvmName`, etc).
 - [ ] Add example if relevant.
 - [ ] Document any changes to public APIs.
 - [ ] Run `make update-api` to update generated api files, if there's public API changes, otherwise the `verify-api-*` CI steps might fail.
 - [ ] Update [CHANGELOG.md](../CHANGELOG.md) or use the label 'skip changelog', otherwise `check changelog` CI step will fail.
 - [ ] If this PR is a `v10.[version]` release branch fix / enhancement, merge it to `main` firstly and then port to `v10.[version]` release branch.

Fixes: < Link to related issues that will be fixed by this pull request, if they exist >

PRs must be submitted under the terms of our Contributor License Agreement [CLA](https://github.com/mapbox/mapbox-maps-android/blob/main/CONTRIBUTING.md#contributor-license-agreement).

### CODE REVIEW

**Review by kiryldz — APPROVED** [review]
🚆 🚆 🚆 
Readme's are not updated on purpose, are they?

**Comment by alexander-kulikovskii** [comment]
> Also leave date empty and revert back readme files. All changes should be done with new release-train

Also leave date empty and revert back readme files. All changes should be done with new release-train

**Comment by alexander-kulikovskii** [comment]
> 🚆 🚆 🚆 Readme's are not updated on purpose, are they?

Also leave date empty and revert back readme files. All changes should be done with new release-train

**Comment by pengdev** [comment]
One question, does the release train push commits to the release branch? and we need to manually port these commits to the main branch I assume? Seems a bit overhead to do the cherry-pick back and forth.

Also would be good to document this process in the internal documentation.

**Review by SevaZhukov — APPROVED** [review]

**Review by pengdev — APPROVED** [review]

**Pull request merged**
