### PR TITLE
Replace the MapTransformDelegate and MapProjectionDelegate with CameraManagerDelegate

### PR DESCRIPTION
**Pull request by Chaoba**
PRs must be submitted under the terms of our Contributor License Agreement [CLA](https://github.com/mapbox/mapbox-maps-android/blob/main/CONTRIBUTING.md#contributor-license-agreement).
Fixes: < Link to related issues that will be fixed by this pull request, if they exist >

## Pull request checklist:
 - [ ] Briefly describe the changes in this PR.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality. If tests were not written, please explain why.
 - [ ] Add example if relevant.
 - [ ] Document any changes to public APIs.
 - [x] Apply changelog label ('breaking change', 'bug :beetle:', 'build', 'docs', 'feature :green_apple:', 'performance :zap:', 'testing :100:') or use the label 'skip changelog'
 - [x] Add an entry inside this element for inclusion in the `mapbox-maps-android` changelog: `<changelog>Replace the MapTransformDelegate and MapProjectionDelegate with CameraManagerDelegate</changelog>`.

### CODE REVIEW

**Review by tobrun — COMMENTED** [review]
Looking at the upstream PR, it seems we have introduced a new interface called `CameraManagerInterface`. This API surfaces matches what we expose with the `CameraManagerDelegate`. Can we use that class instead of CameraManagerDelegate? (sorry, I'm only digging into the details now).

**Comment by tobrun** [comment]
following up after our talk, if we need to expose more API vs the CameraManagerInterface from upstream. We can also have the delegate implement this interface to benefit from automatic API enforcement. Wdyt? Would this be feasible?

**Comment by Chaoba** [comment]
> following up after our talk, if we need to expose more API vs the CameraManagerInterface from upstream. We can also have the delegate implement this interface to benefit from automatic API enforcement. Wdyt? Would this be feasible?

Sounds good.

**Comment by Chaoba** [comment]
Work in another pr https://github.com/mapbox/mapbox-maps-android/pull/293

**Pull request closed without merging**
